### PR TITLE
Added support for GMP scenarios from ManyBugs

### PR DESCRIPTION
**Pull request by ChrisTimperley**

### CODE REVIEW

**Comment by ChrisTimperley** [comment]
Currently fails test cases `p46` and `n3`.

**Comment by afsafzal** [comment]
@ChrisTimperley 14166-14167 passes the failing test. I don't know why

**Comment by ChrisTimperley** [comment]
@afsafzal, do you know which tests are behaving unexpectedly for each of them?

**Comment by afsafzal** [comment]
@ChrisTimperley for 14166 I know `n1` is behaving unexpectedly and `p35` on server (on docker it's passing). for 13420 as you said `p46` and `n3`.  Not sure though.

**Comment by ChrisTimperley** [comment]
Added to https://github.com/ChrisTimperley/ManyBugs. I'll create an issue for the unexpected errors over there.

**Pull request closed without merging**
